# Generated by Django 4.0.2 on 2022-02-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=200)),
                ('parent_id', models.IntegerField(default=-1)),
                ('sum_tree_sum', models.FloatField()),
            ],
        ),
    ]
